version: '2'
services:

  # The Application
  ramrocv_app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  # The Web Server
  ramrocv_web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - ramrocv_app
    ports:
      - 8080:80

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - ramrocv:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=ramrocv"
    ports:
        - "33061:3306"
  
  ramrocv_pma:
    image: phpmyadmin/phpmyadmin
    links:
      - database:database
    ports:
      - 9091:80
    environment:
      - "PMA_HOST=database"
      - "PMA_PORT=3306"

# persisted storage
volumes:
  ramrocv: